#!/bin/sh

GIT_AUTHOR_NAME='Radoslav Bodo'
GIT_AUTHOR_EMAIL='bodik@cesnet.cz'
GIT_COMMITTER_NAME=${GIT_AUTHOR_NAME}
GIT_COMMITTER_EMAIL=${GIT_AUTHOR_EMAIL}
export GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
